### ISSUE TITLE
Nightly behaves slightly differently

### ISSUE THREAD

**Issue by skjnldsv** [R0Wi/nextcloud-appstore-push-action#5]
```yml
        env:
          app_name: ${{ env.APP_NAME }}
          appstore_token: ${{ secrets.APPSTORE_TOKEN }}
          download_url: ${{ steps.attach_to_release.outputs.browser_download_url }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          nightly: ${{ github.event.release.prerelease }}
```

So if you upload a beta, your release must be named `v10.0.0-rc.2` or `v10.0.0-beta.1`
https://github.com/nextcloud/forms/releases/tag/v2.0.0-beta.4
https://github.com/nextcloud/forms/releases/tag/v2.0.0-rc.1

But they must be published as regular releases on the appstore. They will be detected as beta/rc automatically and sent to the appropriate channels only
It's a bit weird, but :shrug: 

https://apps.nextcloud.com/apps/spreed/releases?platform=20#20
![Capture d’écran_2020-11-17_08-15-30](https://user-images.githubusercontent.com/14975046/99357955-216a4d00-28ad-11eb-87ac-488581d4c14f.png)

cc @nickvergessen for confirmation
